### ISSUE TITLE
"node-uuid": "1.4.3" - benchmark\benchmark.js and misc\perf.js brocken

### ISSUE THREAD

**Issue by luscus** [kelektiv/node-uuid#106]
The deprecated API method `BufferClass` is still used in both scripts...

``` js
benchmark\benchmark.js:40
  var buffer = new nodeuuid.BufferClass(16);
               ^
TypeError: undefined is not a function
    at Object.<anonymous> (benchmark\benchmark.js:40:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

And a problem with v1 generation:

``` js

uuid.js:106
    throw new Error('uuid.v1(): Can\'t create more than 10M uuids/sec');
          ^
Error: uuid.v1(): Can't create more than 10M uuids/sec
    at Function.v1 (uuid.js:106:11)
    at Object.<anonymous> (benchmark\benchmark.js:66:56)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

After removing the calls to `BufferClass` and the check block in `index.js` at line 106 the script worked fine:

``` js
# v4
nodeuuid.v4() - using node.js crypto RNG: 243664 uuids/second
nodeuuid.v4() - using Math.random() RNG: 244140 uuids/second
nodeuuid.v4('binary'): 237868 uuids/second
uuid(): 231481 uuids/second
uuid('binary'): 244140 uuids/second
uuidjs.create(4): 410846 uuids/second
140byte.es_v4: 292740 uuids/second

# v1
nodeuuid.v1(): 848896 uuids/second
nodeuuid.v1('binary'): 561797 uuids/second
uuidjs.create(1): 320102 uuids/second
```

**Comment by fedot** [comment]
@luscus, be aware that numbers you get in benchmark are incorrect due to #108
