### ISSUE TITLE
Failed to npm install

### ISSUE THREAD

**Issue by alvipeo** [kelektiv/node-uuid#140]
I'm on Windows 10 and use Node 5.11.x. Trying to add it to my prj and get the following:

```
> node-zopfli@1.4.0 install d:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v47-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@5.11.1 (node-v47 ABI) (falling back to source compile with node-gyp)

d:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\node-zopfli>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

d:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\node-zopfli>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build "--module=d:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\node-zopfli\lib\binding\node-v47-win32-x64\zopfli.node" --module_name=zopfli "--module_path=d:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\node-zopfli\lib\binding\node-v47-win32-x64" )  else (node "" configure --fallback-to-build "--module=d:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\node-zopfli\lib\binding\node-v47-win32-x64\zopfli.node" --module_name=zopfli "--module_path=d:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\node-zopfli\lib\binding\node-v47-win32-x64" )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=d:\\Documents\\Visual Studio 2015\\Projects\\NewsNotifier\\node_modules\\node-zopfli\\lib\\binding\\node-v47-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=d:\\Documents\\Visual Studio 2015\\Projects\\NewsNotifier\\node_modules\\node-zopfli\\lib\\binding\\node-v47-win32-x64"
gyp ERR! cwd d:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\node-zopfli
gyp ERR! node -v v5.11.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=d:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\node-zopfli\lib\binding\node-v47-win32-x64\zopfli.node --module_name=zopfli --module_path=d:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\node-zopfli\lib\binding\node-v47-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (d:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "d:\\Documents\\Visual Studio 2015\\Projects\\NewsNotifier\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd d:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\node-zopfli
node-pre-gyp ERR! node -v v5.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=d:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\node-zopfli\lib\binding\node-v47-win32-x64\zopfli.node --module_name=zopfli --module_path=d:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\node-zopfli\lib\binding\node-v47-win32-x64' (1)
npm WARN install:node-zopfli@1.4.0 node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:node-zopfli@1.4.0 Exit status 1
```

I think I tried it a month age and it used to work. Hm...

**Comment by oculus42** [comment]
I switch between 0.12, 4.4, and 6.2 on my home Windows 10 machine and 0.12, 4.4, and 5.10 on my at work, and have no problem installing node-uuid on any of them.

This does not appear to be an issue with node-uuid. It isn't mentioned anywhere in the output you provide.
