### ISSUE TITLE
using with SystemJs throws ZoneAwareError

### ISSUE THREAD

**Issue by ayyash** [kelektiv/node-uuid#186]
I'm trying it out with systemjs in an angular2 setup, but I keep getting zoneawareerror, here is what I am doing:

in system.config.js
```
 System.config({
    paths: {
      'npm:': '/node_modules/'
    },
    map: {
     'uuid': 'npm:uuid',
 })
```

In typescript:
```
const uuid = require('uuid/v4.js');
// ...
id = uuid(),
```
Getting

```
ZoneAwareError: ...
"(SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:9988/node_modules/uuid/v4.js:1:116)
	    at eval (http://localhost:9988/node_modules/uuid/v4.js:31:4)
	    at eval (http://localhost:9988/node_modules/uuid/v4.js:32:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:9988/node_modules/uuid/lib/rng
	Evaluating http://localhost:9988/node_modules/uuid/v4.js
	Evaluating http://localhost:9988/appscripts/src/app/store/store-data.js
	Evaluating http://localhost:9988/appscripts/src/app/store/common.js
	Evaluating http://localhost:9988/appscripts/src/app/components/home/user.partial.js
	Evaluating http://localhost:9988/appscripts/src/app/core/components.js
	Evaluating http://localhost:9988/appscripts/src/app/modules/routing.module.js
	Evaluating http://localhost:9988/appscripts/src/app/app.module.js
	Evaluating http://localhost:9988/appscripts/src/app/main.js
	Error loading http://localhost:9988/appscripts/src/app/main.js"
```

**Comment by broofa** [comment]
Stack trace is referencing line #'s that don't exist in this projects source.  Almost certainly an issue with your code packaging setup.

https://goo.gl/3JtMgf

**Comment by ayyash** [comment]
It's breaking in uuid/v4.js, I used another library and it worked fine... it must be the way I'm configuring systemjs to use this library, or the way the library is written may be?

**Comment by broofa** [comment]
Track it down a bit further.  Feel free to submit a PR if/when it turns out to be an issue here.
