### ISSUE TITLE
UUID5 not working

### ISSUE THREAD

**Issue by estahn** [kelektiv/node-uuid#192]
```js
> const uuidV4 = require('uuid/v4');
undefined
> uuidV4();
'80b58f8c-43a2-48f2-89ba-6afb8c8c4757'
> const uuidV5 = require('uuid/v5');
Error: Cannot find module 'uuid/v5'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at repl:1:16
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
```

**Comment by hbakhtiyor** [comment]
if it's directly from npm, they not published yet

**Comment by TheJaydox** [comment]
Until published using `npm install kelektiv/node-uuid` to grab the latest from here on GH
