### ISSUE TITLE
How do I install this package'

### ISSUE THREAD

**Issue by wgottschalk** [kelektiv/node-uuid#228]

**Comment by wgottschalk** [comment]
I try running the following command
`npm install uuid`
but I get this error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install', 'uuid' ]
2 info using npm@5.4.2
3 info using node@v6.9.4
4 verbose stack Error: Cannot find module 'node-uuid'
4 verbose stack     at Function.Module._resolveFilename (module.js:469:15)
4 verbose stack     at Function.Module._load (module.js:417:25)
4 verbose stack     at Module.require (module.js:497:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/lib/auth.js:4:12)
4 verbose stack     at Module._compile (module.js:570:32)
4 verbose stack     at Object.Module._extensions..js (module.js:579:10)
4 verbose stack     at Module.load (module.js:487:32)
4 verbose stack     at tryModuleLoad (module.js:446:12)
4 verbose stack     at Function.Module._load (module.js:438:3)
5 verbose cwd /Users/will.gottschalk/dev/chownow/marketplace-react
6 error Darwin 16.7.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "uuid"
8 error node v6.9.4
9 error npm  v5.4.2
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'node-uuid'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```
How do I install this package if I need it to exist to run npm?

**Comment by broofa** [comment]
This is working for me (see below), and 100K's of other users of this module and npm, so my default assumption here has to be this is something unique to your setup.

Maybe start out by making an empty directory and seeing if `npm --verbose install uuid` still causes the issue.  If so, try reinstalling node & npm.  If not, then it's something specific to your project, and you'll have to dig deeper to figure it out.

I'm gonna close this for now since I'm 99+% sure this isn't an issue with this module.
```
kieffer@MacBook-Pro-3$ cd /tmp/foo

kieffer@MacBook-Pro-3$ ls -Fla
total 0
drwxr-xr-x   2 kieffer  wheel   68 Oct 12 15:41 ./
drwxrwxrwt  25 root     wheel  850 Oct 12 16:46 ../

kieffer@MacBook-Pro-3$ npm install --verbose uuid
npm info it worked if it ends with ok
npm verb cli [ '/Users/kieffer/.nvm/versions/node/v7.10.1/bin/node',
npm verb cli   '/Users/kieffer/.nvm/versions/node/v7.10.1/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'uuid' ]
npm info using npm@5.4.2
npm info using node@v7.10.1
npm verb npm-session f8a4a1a735e49789
npm http fetch GET 304 https://registry.npmjs.org/uuid 300ms (from cache)
npm verb correctMkdir /Users/kieffer/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/kieffer/.npm/_locks/staging-c1f8adb6ab6386ed.lock for /private/tmp/node_modules/.staging
npm info lifecycle uuid@3.1.0~preuninstall: uuid@3.1.0
npm info lifecycle uuid@3.1.0~uninstall: uuid@3.1.0
npm verb unbuild rmStuff uuid@3.1.0 from /private/tmp/node_modules
npm info lifecycle uuid@3.1.0~postuninstall: uuid@3.1.0
npm info lifecycle uuid@3.1.0~preinstall: uuid@3.1.0
npm info linkStuff uuid@3.1.0
npm verb linkBins uuid@3.1.0
npm verb linkBins [ { uuid: './bin/uuid' },
npm verb linkBins   '/private/tmp/node_modules/.bin',
npm verb linkBins   false ]
npm verb linkMans uuid@3.1.0
npm info lifecycle uuid@3.1.0~install: uuid@3.1.0
npm info lifecycle uuid@3.1.0~postinstall: uuid@3.1.0
npm verb unlock done using /Users/kieffer/.npm/_locks/staging-c1f8adb6ab6386ed.lock for /private/tmp/node_modules/.staging
npm WARN saveError ENOENT: no such file or directory, open '/private/tmp/package.json'
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/package.json'
npm verb enoent This is related to npm not being able to find a file.
npm verb enoent
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

+ uuid@3.1.0
updated 1 package in 1.248s
npm verb exit [ 0, true ]
npm info ok

kieffer@MacBook-Pro-3$```
