### ISSUE TITLE
npm install uuid leads to EINVAL error

### ISSUE THREAD

**Issue by Alexsey** [kelektiv/node-uuid#234]
Just execute
```
npm i uuid
```
and got
```
npm [...]@1.0.0 No description
npm [...]@1.0.0 No license field.

npm ERR! code EINVAL
npm ERR! EINVAL: invalid argument, read

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[...]\AppData\Roaming\npm-cache\_logs\2017-11-14T14_43_30_234Z-debug.log
```
I'm using Windows 10 Pro and have tried NodeJS 9.1.0 + npm 5.5.1 and NodeJS 8.9.1 + npm 5.4.2 - the errors are the same. Also I have tried to `npm i uuid@3.0.1` and `npm i uuid@3.0.0` and `npm i uuid@1.4.7` - nothing changes

Here is an error file log from the issue:
[2017-11-14T14_43_30_234Z-debug.log](https://github.com/kelektiv/node-uuid/files/1471488/2017-11-14T14_43_30_234Z-debug.log)

**Comment by broofa** [comment]
Possibly an issue with `gentlyrm`?
```
863 verbose stack Error: EINVAL: invalid argument, read
863 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\utils\gently-rm.js:275:7
863 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
863 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:287:18
863 verbose stack     at FSReqWrap.oncomplete (fs.js:167:5)
```
https://github.com/yarnpkg/yarn/pull/772 also mentions this issue in relation to Windows Subsystem for Linux (WSL), but that's not a world I'm familiar with (and happier for it. ;-) )

**Comment by broofa** [comment]
Have you tried doing `npm i install` in a clean directory?  It looks like you've got a ton of other stuff in your working directory.  FWIW, here's what I get when I do `npm i -ddd uuid`:
```
kieffer@MacBook-Pro-3$ npm i -ddd uuid
npm info it worked if it ends with ok
npm verb cli [ '/Users/kieffer/.nvm/versions/node/v7.10.1/bin/node',
npm verb cli   '/Users/kieffer/.nvm/versions/node/v7.10.1/bin/npm',
npm verb cli   'i',
npm verb cli   '-ddd',
npm verb cli   'uuid' ]
npm info using npm@5.5.1
npm info using node@v7.10.1
npm verb npm-session 91f532a5b3399d96
npm sill install loadCurrentTree
npm sill install readLocalPackageData
npm http fetch GET 200 https://registry.npmjs.org/uuid 28ms (from cache)
npm sill pacote tag manifest for uuid@latest fetched in 54ms
npm sill install loadIdealTree
npm sill install cloneCurrentTreeToIdealTree
npm sill install loadShrinkwrap
npm sill install loadAllDepsIntoIdealTree
npm sill resolveWithNewModule uuid@3.1.0 checking installable status
npm sill currentTree work
npm sill idealTree work
npm sill idealTree `-- uuid@3.1.0
npm sill install generateActionsToTake
npm sill diffTrees action count 1
npm sill diffTrees add uuid@3.1.0
npm sill decomposeActions action count 8
npm sill decomposeActions fetch uuid@3.1.0
npm sill decomposeActions extract uuid@3.1.0
npm sill decomposeActions preinstall uuid@3.1.0
npm sill decomposeActions build uuid@3.1.0
npm sill decomposeActions install uuid@3.1.0
npm sill decomposeActions postinstall uuid@3.1.0
npm sill decomposeActions finalize uuid@3.1.0
npm sill decomposeActions refresh-package-json uuid@3.1.0
npm sill install executeActions
npm sill doSerial global-install 8
npm verb correctMkdir /Users/kieffer/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/kieffer/.npm/_locks/staging-27d7381a165c61a7.lock for /Users/kieffer/work/node_modules/.staging
npm sill doParallel extract 8
npm sill extract uuid@3.1.0
sill pacote trying uuid@https://registry.npmjs.org/uuid/-/uuid-3.1.0.tgz by hash: sha512-DIWtzUkw04M4k3bf1IcpS2tngXEL26YUD2M0tMDUpnUrz2hgzUBlD55a4FjdLGPvfHxS6uluGWvaVEqgBcVa+g==
sill pacote uuid@https://registry.npmjs.org/uuid/-/uuid-3.1.0.tgz extracted to /Users/kieffer/work/node_modules/.staging/uuid-48044da6 by content address 58ms
npm sill doReverseSerial unbuild 8
npm sill doSerial remove 8
npm sill doSerial move 8
npm sill doSerial finalize 8
npm sill finalize /Users/kieffer/work/node_modules/uuid
npm sill doParallel refresh-package-json 8
npm sill refresh-package-json /Users/kieffer/work/node_modules/uuid
npm sill doParallel preinstall 8
npm sill preinstall uuid@3.1.0
npm info lifecycle uuid@3.1.0~preinstall: uuid@3.1.0
npm sill doSerial build 8
npm sill build uuid@3.1.0
npm info linkStuff uuid@3.1.0
npm sill linkStuff uuid@3.1.0 has /Users/kieffer/work/node_modules as its parent node_modules
npm verb linkBins uuid@3.1.0
npm verb linkBins [ { uuid: './bin/uuid' },
npm verb linkBins   '/Users/kieffer/work/node_modules/.bin',
npm verb linkBins   false ]
npm verb linkMans uuid@3.1.0
npm sill doSerial global-link 8
npm sill doParallel update-linked 8
npm sill doSerial install 8
npm sill install uuid@3.1.0
npm info lifecycle uuid@3.1.0~install: uuid@3.1.0
npm sill doSerial postinstall 8
npm sill postinstall uuid@3.1.0
npm info lifecycle uuid@3.1.0~postinstall: uuid@3.1.0
npm verb unlock done using /Users/kieffer/.npm/_locks/staging-27d7381a165c61a7.lock for /Users/kieffer/work/node_modules/.staging
npm sill install saveToDependencies
npm WARN saveError ENOENT: no such file or directory, open '/Users/kieffer/work/package.json'
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm notice created a lockfile as package-lock.json. You should commit this file.
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN enoent ENOENT: no such file or directory, open '/Users/kieffer/work/package.json'
npm verb enoent This is related to npm not being able to find a file.
npm verb enoent
npm WARN work No description
npm WARN work No repository field.
npm WARN work No README data
npm WARN work No license field.

npm sill install printInstalled
+ uuid@3.1.0
added 1 package in 0.829s
npm verb exit [ 0, true ]
npm info ok

kieffer@MacBook-Pro-3$
```

**Comment by Alexsey** [comment]
Yes, you where right - clean install went well. Thank you for your help!
