### ISSUE TITLE
Error: Uncaught [TypeError: v4_1.default is not a function]

### ISSUE THREAD

**Issue by zakariaharti** [kelektiv/node-uuid#300]
``` 
Error: Uncaught [TypeError: v4_1.default is not a function]
        at reportException (Z:\opensource\react-notifiable\node_modules\jsdom\li
b\jsdom\living\helpers\runtime-script-errors.js:66:24)
        at invokeEventListeners (Z:\opensource\react-notifiable\node_modules\jsd
om\lib\jsdom\living\events\EventTarget-impl.js:209:9)
        at HTMLUnknownElementImpl._dispatch (Z:\opensource\react-notifiable\node
_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (Z:\opensource\react-notifiable\
node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (Z:\opensource\react-notifiable\
node_modules\jsdom\lib\jsdom\living\nodes\HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (Z:\opensource\react-notifiable\node
_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (Z:\opensource\react-notifiable\node_
modules\react-dom\cjs\react-dom.development.js:199:16)
        at invokeGuardedCallback (Z:\opensource\react-notifiable\node_modules\re
act-dom\cjs\react-dom.development.js:256:31)
        at replayUnitOfWork (Z:\opensource\react-notifiable\node_modules\react-d
om\cjs\react-dom.development.js:16366:5)
        at renderRoot (Z:\opensource\react-notifiable\node_modules\react-dom\cjs
\react-dom.development.js:17148:11) TypeError: v4_1.default is not a function
        at Z:\opensource\react-notifiable\src\components\Notification.tsx:124:28

        at Array.map (<anonymous>)
        at Notification._this.renderButtons (Z:\opensource\react-notifiable\src\
components\Notification.tsx:122:20)
        at Notification.Object.<anonymous>.Notification.render (Z:\opensource\re
act-notifiable\src\components\Notification.tsx:190:23)
        at finishClassComponent (Z:\opensource\react-notifiable\node_modules\rea
ct-dom\cjs\react-dom.development.js:13727:31)
        at updateClassComponent (Z:\opensource\react-notifiable\node_modules\rea
ct-dom\cjs\react-dom.development.js:13690:10)
        at beginWork (Z:\opensource\react-notifiable\node_modules\react-dom\cjs\
react-dom.development.js:14489:16)
        at performUnitOfWork (Z:\opensource\react-notifiable\node_modules\react-
dom\cjs\react-dom.development.js:17014:12)
        at workLoop (Z:\opensource\react-notifiable\node_modules\react-dom\cjs\r
eact-dom.development.js:17054:24)
        at HTMLUnknownElement.callCallback (Z:\opensource\react-notifiable\node_
modules\react-dom\cjs\react-dom.development.js:149:14)
        at invokeEventListeners (Z:\opensource\react-notifiable\node_modules\jsd
om\lib\jsdom\living\events\EventTarget-impl.js:193:27)
        at HTMLUnknownElementImpl._dispatch (Z:\opensource\react-notifiable\node
_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (Z:\opensource\react-notifiable\
node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (Z:\opensource\react-notifiable\
node_modules\jsdom\lib\jsdom\living\nodes\HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (Z:\opensource\react-notifiable\node
_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (Z:\opensource\react-notifiable\node_
modules\react-dom\cjs\react-dom.development.js:199:16)
        at invokeGuardedCallback (Z:\opensource\react-notifiable\node_modules\re
act-dom\cjs\react-dom.development.js:256:31)
        at replayUnitOfWork (Z:\opensource\react-notifiable\node_modules\react-d
om\cjs\react-dom.development.js:16366:5)
        at renderRoot (Z:\opensource\react-notifiable\node_modules\react-dom\cjs
\react-dom.development.js:17148:11)
        at performWorkOnRoot (Z:\opensource\react-notifiable\node_modules\react-
dom\cjs\react-dom.development.js:17993:7)
        at performWork (Z:\opensource\react-notifiable\node_modules\react-dom\cj
s\react-dom.development.js:17901:7)
        at performSyncWork (Z:\opensource\react-notifiable\node_modules\react-do
m\cjs\react-dom.development.js:17873:3)
        at requestWork (Z:\opensource\react-notifiable\node_modules\react-dom\cj
s\react-dom.development.js:17761:5)
        at scheduleWork (Z:\opensource\react-notifiable\node_modules\react-dom\c
js\react-dom.development.js:17566:5)
        at scheduleRootUpdate (Z:\opensource\react-notifiable\node_modules\react
-dom\cjs\react-dom.development.js:18240:3)
        at updateContainerAtExpirationTime (Z:\opensource\react-notifiable\node_
modules\react-dom\cjs\react-dom.development.js:18267:10)
        at updateContainer (Z:\opensource\react-notifiable\node_modules\react-do
m\cjs\react-dom.development.js:18324:10)
        at ReactRoot.Object.<anonymous>.ReactRoot.render (Z:\opensource\react-no
tifiable\node_modules\react-dom\cjs\react-dom.development.js:18586:3)
        at Z:\opensource\react-notifiable\node_modules\react-dom\cjs\react-dom.d
evelopment.js:18726:14
        at unbatchedUpdates (Z:\opensource\react-notifiable\node_modules\react-d
om\cjs\react-dom.development.js:18124:10)
        at legacyRenderSubtreeIntoContainer (Z:\opensource\react-notifiable\node
_modules\react-dom\cjs\react-dom.development.js:18722:5)
        at Object.render (Z:\opensource\react-notifiable\node_modules\react-dom\
cjs\react-dom.development.js:18783:12)
        at Object.render (Z:\opensource\react-notifiable\node_modules\enzyme-ada
pter-react-16\build\ReactSixteenAdapter.js:348:114)
        at new ReactWrapper (Z:\opensource\react-notifiable\node_modules\enzyme\
build\ReactWrapper.js:130:16)
        at Object.mount (Z:\opensource\react-notifiable\node_modules\enzyme\buil
d\mount.js:21:10)
        at Object.<anonymous> (Z:\opensource\react-notifiable\src\components\Not
ification.spec.tsx:21:80)
        at Object.asyncJestTest (Z:\opensource\react-notifiable\node_modules\jes
t-jasmine2\build\jasmine_async.js:108:37)
        at resolve (Z:\opensource\react-notifiable\node_modules\jest-jasmine2\bu
ild\queue_runner.js:56:12)
        at new Promise (<anonymous>)
        at mapper (Z:\opensource\react-notifiable\node_modules\jest-jasmine2\bui
ld\queue_runner.js:43:19)
        at promise.then (Z:\opensource\react-notifiable\node_modules\jest-jasmin
e2\build\queue_runner.js:87:41)
        at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by broofa** [comment]
`uuid` does not appear anywhere in the stack. No context provided.  No instructions for reproducing the error.  :-/

Based on cursory lool, 'probably an issue with packager configuration?  Please investigate this further.  If/when you identify a concrete issue with this module, comment here and I'll consider reopening.

**Comment by mlg87** [comment]
this looks like its happening bc `uuid/v4` isnt being mocked in a jest test suite. something we use to get around this is:
```ts
jest.mock('uuid/v4', () => {

    let count = 0;
    return {
        default: () => {

            const key = `test-key-${count}`;
            count++;
            return key;

        }
    };

});
```
