### ISSUE TITLE
Activating extension 'test.completions-sample' failed: Cannot find module 'uuid/v4'

### ISSUE THREAD

**Issue by syedirfan7** [kelektiv/node-uuid#305]
Hello Team ,
i already have the uuid included in my package.json and it runs very well while running the extension in debug mode but when it is installed as vsix  in VSCode it says 

`extensionService.ts:800 
Activating extension 'test.completions-sample' failed: Cannot find module 'uuid/v4'.
t._logMessageInConsole @ extensionService.ts:800
t._logOrShowMessage @ extensionService.ts:814
e.$localShowMessage @ mainThreadExtensionService.ts:32
t._doInvokeHandler @ rpcProtocol.ts:390
t._invokeHandler @ rpcProtocol.ts:375
t._receiveRequest @ rpcProtocol.ts:295
t._receiveOneMessage @ rpcProtocol.ts:225
(anonymous) @ rpcProtocol.ts:100
e.fire @ event.ts:567
s @ ipc.net.ts:295
(anonymous) @ ipc.net.ts:302
e.fire @ event.ts:567
a @ ipc.net.ts:103
_socketDataListener @ ipc.net.ts:132
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
console.ts:134 [Extension Host] Activating extension 'test.completions-sample' failed: Cannot find module 'uuid/v4'.
t.log @ console.ts:134
e.$logExtensionHostMessage @ mainThreadConsole.ts:39
t._doInvokeHandler @ rpcProtocol.ts:390
t._invokeHandler @ rpcProtocol.ts:375
t._receiveRequest @ rpcProtocol.ts:295
t._receiveOneMessage @ rpcProtocol.ts:225
(anonymous) @ rpcProtocol.ts:100
e.fire @ event.ts:567
s @ ipc.net.ts:295
(anonymous) @ ipc.net.ts:302
e.fire @ event.ts:567
a @ ipc.net.ts:103
_socketDataListener @ ipc.net.ts:132
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
console.ts:134 [Extension Host] Activating extension `test.completions-sample` failed:  Cannot find module 'uuid/v4' [Extension Host] Here is the error stack:  Error: Cannot find module 'uuid/v4'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
	at Function.Module._load (internal/modules/cjs/loader.js:528:25)
	at Function.t._load (c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:751:268)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:730:770)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:674:774)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\irsy271621\.vscode\extensions\test.completions-sample-0.0.2\out\extension.js:7:16)
	at Object.<anonymous> (C:\Users\irsy271621\.vscode\extensions\test.completions-sample-0.0.2\out\extension.js:47:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:751:268)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:730:770)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:674:774)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:31:542)
	at c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:740:5
	at t._doActivateExtension (c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:740:113)
	at t._activateExtension (c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:738:785)
	at Object.actualActivateExtension (c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:735:633)
	at e._activateExtension (c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:330:969)
	at c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:330:592
	at Array.map (<anonymous>)
	at e._activateExtensions (c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:330:567)
	at e.activateByEvent (c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:328:462)
	at t._activateByEvent (c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:737:174)
	at t._handleEagerExtensions (c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:741:590)
	at c:\Users\irsy271621\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:745:298
`

**Comment by broofa** [comment]
Issue with VSCode or VS module packager.  Not an issue with this project's code.
